export const mySkills = [
  { title: "NodeJS", icon: "nodejs" },
  { title: "ExpressJS", icon: "express" },
  { title: "Docker", icon: "docker" },
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "shadcn/ui", icon: "shadcn" },
  { title: "Material UI", icon: "material" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "ReactJS", icon: "react" },
  { title: "Redux", icon: "redux" },
  { title: "NextJS", icon: "nextjs" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "PostgreSQL", icon: "postgresql" },
  { title: "Supabase", icon: "supabase" },
  { title: "GraphQL", icon: "graphql" },
  { title: "Docker", icon: "docker" },
  { title: "Vercel", icon: "vercel" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "github" },
  { title: "ESLint", icon: "eslint" },
  { title: "Postman", icon: "postman" },
  { title: "npm", icon: "npm" },
  { title: "LangChain", icon: "langchain" },
  { title: "Pinecone", icon: "pinecone" },
  { title: "OpenAI", icon: "openai" },
  { title: "Azure", icon: "azure" },
  { title: "AWS", icon: "aws" },

];
